export enum TipoServicio {
  SMYTREFRENDO = 'T: 08',
  SMYTREFRENDOCAMBIOPROPIETARIO = 'T: 04',
  ALTAVEHICULOCAMBIOPROPIETARIO = 'T: 12',
  ALTAVEHICULOSINREGISTRO = 'T: 16',
  SUSTITUCIONPLACACAMBIOPROPIETARIO = 'T: 09',
  CAMBIOPROPIETARIO = 'T: 04',
  CAMBIOPROPIETARIOBAJA = 'T: 15',
  SMYTALTAVEHICULONUEVO = 'T: 01',
  SMYTALTAVEHICULOUSADO = 'T: 13',//'T: 10',
  SMYTBAJA = 'T: 03',
  SMYTTARJETADUPLICADA = 'T: 05',
  SMYTSUSTITUCIONPLACA = 'T: 02'
}
